trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: asottile
      type: github
      endpoint: github
      name: asottile/azure-pipeline-templates
      ref: refs/tags/v2.0.0

jobs:
- template: job--pre-commit.yml@asottile
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py38]
    os: windows
    coverage: false
    wheel_tags: true
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py38]
    os: macos
    coverage: false
    wheel_tags: true
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py38]
    os: linux
    coverage: false
